### ISSUE TITLE
ruby_block[bdb_config] - ldif doesn't exist

### ISSUE THREAD

**Issue by Raven24** [carguel/chef-cookbook-ca-openldap#17]
On CentOS 7 the openldap-server package currently is 2.4.40
The docs for openldap 2.4 say that the [bdb was superseded by hdb](http://www.openldap.org/doc/admin24/backends.html) and indeed, if I try to run the server recipe I get this error:

```
ArgumentError: ruby_block[bdb_config] (ca_openldap::server line 96) had an error: ArgumentError: File '/etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif' does not exist
```

there is now a [...]hdb.ldif file that needs to be modified instead. It appears simply changing the filename in that case is enough.

**Comment by carguel** [comment]
It has been fixed in 0.6 (release coming).

The new attribute node['ca_openldap']['db_backend'] allows to set the expected slapd backend.
